---
title: "The Blood of Christ Compels Them: State Religiosity and State Population Mobility During the Coronavirus (COVID-19) Pandemic"
author: "Terrence Hill, Kelsey Gonzalez, Amy Burdette"
date: "April 15, 2020"
output:
  pdf_document
header-includes: \usepackage{dcolumn}
editor_options:
  chunk_output_type: console
classoption: portrait
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(MASS)
library(stargazer)
library(sjPlot)
library(sjmisc)

covid <- read_csv("religiosity_mobility.csv")

```

```{r table 1, results='asis'}
base_model <-   rlm(mobility ~ week_f + religiosity_c + age_c + black_c+ unemployment_c + density_c + mobility_lag_1_c + SAH_days.y + republican_governor + week_f:religiosity_c, data = covid)

stargazer(
  rlm(mobility ~ week_f , data = covid),
  rlm(mobility ~ week_f + religiosity_c + age_c + black_c+ 
        unemployment_c + density_c + mobility_lag_1_c, data = covid),
  rlm(mobility ~ week_f + religiosity_c + age_c + black_c+ 
        unemployment_c + density_c + mobility_lag_1_c + 
        SAH_days.y + republican_governor, data = covid),
  base_model,
  title="Robust Regression Results for State Mobility, controlling for week", 
  covariate.labels = c(
    # "02/24",
    "03/02",
    "03/09",
    "03/16",
    "03/23",
    "03/30",
    "04/06",
    "04/13",
    "Religiosity Index",
    "Median Age",
    "Percent Black",
    "Unemployment Rate",
    "Population Density",
    "Mobility Lag",
    "Days under stay-at-home order",
    "Republican Governor",
    # "02/24 x Religiosity",
    "03/02 x Religiosity",
    "03/09 x Religiosity",
    "03/16 x Religiosity",
    "03/23 x Religiosity",
    "03/30 x Religiosity",
    "04/06 x Religiosity",
    "04/13 x Religiosity"),
  align = TRUE,
  # type = "text",
  star.cutoffs = c(.05, .01, .001), 
  no.space = T, 
  digits = 2,
  omit.stat = c("f", "ser"),
  column.sep.width = "-15pt")
```

```{r fig 1 interaction plot}
fig_1 <- plot_model(base_model, 
           type = "pred", 
           terms = c("week_f", "religiosity_c"))

fig_1 <- as.data.frame(fig_1$data) %>% 
      mutate(x = fct_recode(as.factor(x), 
                        "02/24" = "1", 
                        "03/02" = "2", 
                        "03/09" = "3",
                        "03/16" = "4",
                        "03/23" = "5", 
                        "03/30" = "6",
                        "04/06" = "7", 
                        "04/13" = "8"),
             group_col = fct_recode(as.factor(group_col), 
                        "Low Religiosity" = "-0.96", 
                        "Moderate Religiosity" = "0", 
                        "High Religiosity" = "0.96"
                        ))


ggplot(fig_1, aes(x = x, y = predicted, group = group_col)) + 
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, group = group_col, fill = group_col), alpha = .5)  +
  geom_line(aes(color = group_col, linetype = group_col)) +
  scale_linetype_manual("Religiosity", values=c("solid","dashed", "solid"), 
                        guide = guide_legend(reverse = TRUE) )+
  scale_color_manual("Religiosity", values=c('#808080', '#808080','#000000'), 
                     guide = guide_legend(reverse = TRUE) ) +
  scale_fill_manual("Religiosity", values=c('#FFFFFF', '#808080','#000000'), 
                    guide = guide_legend(reverse = TRUE) ) +
  xlab("Week") +  
  scale_x_discrete(expand = c(0, .1)) +
  ylab ("Mobility") +
  theme(legend.position=c(0.2,0.2))+
  labs(title = "FIGURE 1: Adjusted State Mobility Trends by State Religiosity") 

ggsave(filename = "fig_1.png")

```

```{r robust standard errors, include=FALSE}
library(miceadds)
mod1 <- round(summary(lm.cluster(mobility ~ week_f + religiosity_c + age_c + black_c+ unemployment_c + density_c + mobility_lag_1_c + SAH_days.y + republican_governor, data = covid,  cluster = "state")), 3)
mod1
```

```{r fig 2 maps}
library(usmap)
library(patchwork)
maps <- covid %>% filter(week_f == "04/13") %>% dplyr::select(state, religiosity_c, mobility)
  
diff <- covid %>% 
  # filter(state %in% c("Massachusetts", "Alabama", "Indiana")) %>% 
  filter(week_f == "04/13" | week_f == "02/24" ) %>% 
  dplyr::select(state, mobility, week_f) %>% 
  pivot_wider(id_cols = state, 
              names_from = week_f, 
              values_from = mobility)  %>% 
  mutate(diff = `04/13` / `02/24`) %>% 
  left_join(covid %>% dplyr::select(state, religiosity_c) %>% unique())
indi <- plot_usmap("states", include = "Indiana",size = 1.5)  +
       annotate(geom = "label", 
           x = 1176423,
           y = -424024.1, 
           label = "INDIANA\nReligiosity: Moderate\n Overall Mobility Reduction: 32%", 
           hjust = "center", 
           vjust = "center", 
           size = 2)

alab <- plot_usmap("states", include = "Alabama",size = 1.5)  +
       annotate(geom = "label", 
           x = 1235808,
           y = -1208907, 
           label = "ALABAMA\nReligiosity: High\n Overall Mobility Reduction: 22%", 
           hjust = "center", 
           vjust = "center", 
           size = 2)

mass <- plot_usmap("states", include = "Massachusetts",size = 1.5)  +
       annotate(geom = "label", 
           x = 2281940,
           y = 131592.95, 
           label = "MASSACHUSETTS\nReligiosity: Low\n Overall Mobility Reduction: 64%", 
           hjust = "center", 
           vjust = "center", 
           size = 2)


mass + indi + alab + plot_layout(ncol=3,widths=c(2,1,1)) +
  plot_annotation(title = "FIGURE 2: Percent Change in Mobility (2/24 to 4/13) by Religious Exemplar States")

ggsave(filename="fig_2.png", width = 8, height = 3)

```

```{r table 2 SAH x relig table, results='asis'}
SAH_Relig <-  rlm(mobility ~ week_f + religiosity_c + age_c + black_c+ unemployment_c + density_c + mobility_lag_1_c + SAH_days.y + republican_governor + SAH_days.y:religiosity_c, data = covid)

stargazer(
  rlm(mobility ~ week_f , data = covid),
  rlm(mobility ~ week_f + religiosity_c + age_c + black_c+ unemployment_c + density_c + mobility_lag_1_c, data = covid),
  rlm(mobility ~ week_f + religiosity_c + age_c + black_c+ unemployment_c + density_c + mobility_lag_1_c + SAH_days.y + republican_governor, data = covid),
   SAH_Relig,
  title="Robust Regression Results for State Mobility, controlling for week", 
  covariate.labels = c(
    # "02/24",
    "03/02",
    "03/09",
    "03/16",
    "03/23",
    "03/30",
    "04/06",
    "04/13",
    "Religiosity Index",
    "Median Age",
    "Percent Black",
    "Unemployment Rate",
    "Population Density",
    "Mobility Lag",
    "Days under stay-at-home order",
    "Republican Governor",
    "Days under SAH x Religiosity"),
  align = TRUE,
  # type = "text",
  star.cutoffs = c(.05, .01, .001), 
  no.space = T, 
  digits = 2,
  omit.stat = c("f", "ser"),
  column.sep.width = "-15pt")
```

```{r fig 3 SAH x relig }
fig_3 <- plot_model(SAH_Relig, 
           type = "pred", 
           terms = c("SAH_days.y","religiosity_c"))

fig_3 <- as.data.frame(fig_3$data) %>% 
      mutate(group_col = fct_recode(as.factor(group_col), 
                        "Low Religiosity" = "-0.96", 
                        "Moderate Religiosity" = "0", 
                        "High Religiosity" = "0.96"
                        ))


ggplot(fig_3, aes(x = x, y = predicted, group = group_col)) + 
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, group = group_col, fill = group_col), alpha = .5)  +
  geom_line(aes(color = group_col, linetype = group_col)) +
  scale_linetype_manual("Religiosity", values=c("solid","dashed", "solid"), 
                        guide = guide_legend(reverse = TRUE) )+
  scale_color_manual("Religiosity", values=c('#808080', '#808080','#000000'), 
                     guide = guide_legend(reverse = TRUE) ) +
  scale_fill_manual("Religiosity", values=c('#FFFFFF', '#808080','#000000'), 
                    guide = guide_legend(reverse = TRUE) ) +
  xlab("Days under Stay at Home Order") +  
  scale_x_continuous(expand = c(0, .1)) +
  ylab ("Mobility") +
  theme(legend.position=c(0.2,0.2))+
  labs(title = "FIGURE 3: Adjusted State Mobility by Days under Stay-at-Home Order\nand State Religiosity") 

ggsave(filename = "fig_3.png")

```

